spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root

server:
  port: 9090
mybatis:
  configuration:
    # 开启驼峰命名和下划线命名转换
    map-underscore-to-camel-case: true
